### PR TITLE
Take advantage of Batch Requests

### PR DESCRIPTION
**Pull request by xblitz**
* Take advantage of [Batch Requests](https://developers.google.com/gmail/api/guides/batch) 
* Some code cleanup and removed unneeded files

### CODE REVIEW

**Comment by xblitz** [comment]
Let me know if you want this or have any questions/suggestions,  I've already used it locally in my project,  the batch process works and if any specific mail fails, others will still be sent but raise the last exception,  if fail_silently is true, it will return the number of non-failed messages

**Comment by dolfim** [comment]
Hi @xblitz, I think that using the batch request is a great improvement, thanks.
However, I'm not sure about removing `gmailapi_backend/bin/gmail_oauth2.py`, because (1) it is referenced in the setup.py and the README, (2) it is anyway still required to run once the oauth2 authentication flow and pass the `refresh_token` .

**Comment by xblitz** [comment]
Ohhh right,  I though it was an some leftover in a commit, actually though it was the google oauth lib,  but now I see its the utility to generate tokens and such.  Makes sense, and anyway doesn't have anything to do with my PR , let me fix this

**Comment by xblitz** [comment]
let me know if this is good for you or if you have other concerns :)

**Review by dolfim — APPROVED** [review]
Thanks, it is all working fine!

**Pull request merged**
